# .github/workflows/daily-download.yml
name: Download the file from SBI server, at 3:00 PM everyday
on:
  schedule:
    # Runs every 5 minutes from 8:00 AM to 5:00 PM IST (2:30 AM to 11:30 AM UTC)
    # IST is UTC+5:30, so 8:00 AM IST = 2:30 AM UTC, 5:00 PM IST = 11:30 AM UTC
    - cron: "*/5 2-11 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Download Rates FILE
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
      # libmagic is used to detect MIME type
    - name: Install libmagic
      run: |
        sudo apt-get update
        sudo apt-get install -y libmagic1
      # poppler is used to convert pdf to images
    - name: Install poppler
      run: |
        sudo apt-get install -y poppler-utils
    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download and save file
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: python main.py
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: "dddd, MMMM Do YYYY, h:mm:ss a"
        utcOffset: "+05:30"
      # Commit the PDF and the updated rates in csv
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto Commit: SBI rates at ${{ steps.current-time.outputs.formattedTime }}"
